[package]
name = "wry-app-dragout"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
base64.workspace = true
drag.workspace = true
serde.workspace = true
serde_json.workspace = true
wry.workspace = true
dunce.workspace = true